export const bookingPolicies = {
  en: {
    termsEyebrow: "Terms",
    termsTitle: "Clear terms before you reserve.",
    termsLead: "These terms apply to ASCENSION SENSES · Da Nang, January 12–26, 2027.",
    attendanceLabel: "View attendance options",
    reservationHeading: "Reservation and payment",
    reservation: "A USD $300 deposit reserves your place. The remaining programme balance is due 30 days before January 12, 2027.",
    cancellationHeading: "Cancellation policy",
    cancellation: [
      "ASCENSION Da Nang is scheduled for January 12–26, 2027, with final confirmation by November 1, 2026. If the event is not confirmed by that deadline, cancelled or rescheduled by ASCENSION, guests may choose a full refund of programme payments or an optional full-value credit toward a future edition.",
      "Guests who voluntarily cancel before their programme begins may request a refund less 10% of programme payments received, where legally permitted, or choose full-value credit toward a future edition within 24 months. Any price difference applies when rebooking. Statutory cancellation rights take precedence, and no administration fee will be deducted where a full refund is legally required.",
      "Requests may be emailed to ",
      "Refunds will be processed within 15 days to the original payment method. Credits require the guest’s agreement.",
      "Flights, accommodation, transfers and separately booked services follow their providers’ own terms. Wait for written event confirmation before making non-refundable travel arrangements.",
    ],
    quebecHeading: "Québec statutory cancellation rights",
    quebec: "For eligible distance-contract cancellations under Québec consumer law, if reimbursement has not been received within 15 days of the cancellation notice, a guest who paid by credit card may request a chargeback within the following 60 days. The issuer must acknowledge receipt within 30 days and credit the account within the earlier of 90 days or two complete statement periods. If the applicable deadline passes without a credit, the consumer may send a formal notice to the issuer. Eligibility, exceptions and statutory deadlines apply.",
    quebecLinkLabel: "Learn about Québec online-purchase cancellation rights",
    travelHeading: "Travel and accommodation",
    travel: "Accommodation, flights and local transfers are not included in the ASCENSION programme price. Guests select and book their own accommodation unless a confirmed offer explicitly states otherwise.",
    wellnessHeading: "Wellness and educational experience",
    wellness: "ASCENSION is a wellness and educational experience, not medical care. Its programming does not replace medical diagnosis, treatment or professional healthcare. Participants remain responsible for deciding whether an activity is appropriate for them and for seeking qualified medical advice when needed.",
    faq: "ASCENSION Da Nang will be finally confirmed by November 1, 2026. If ASCENSION does not confirm, cancels or reschedules the event, choose a full programme-payment refund or full-value future-edition credit. If you cancel voluntarily before the programme begins, you may request a refund less 10% where legally permitted or a 24-month full-value credit; statutory rights take precedence. Refunds are processed within 15 days. See the Terms for the complete policy.",
    bookingSummary: "Final confirmation is due by November 1, 2026. Review the cancellation policy before payment.",
    bookingTermsLabel: "Read cancellation and booking terms",
  },
  fr: {
    termsEyebrow: "Conditions",
    termsTitle: "Des conditions claires avant de réserver.",
    termsLead: "Ces conditions s’appliquent à ASCENSION SENSES · Da Nang, du 12 au 26 janvier 2027.",
    attendanceLabel: "Voir les options de participation",
    reservationHeading: "Réservation et paiement",
    reservation: "Un acompte de 300 USD réserve votre place. Le solde du programme est dû 30 jours avant le 12 janvier 2027.",
    cancellationHeading: "Politique d’annulation",
    cancellation: [
      "ASCENSION Da Nang est prévu du 12 au 26 janvier 2027, avec une confirmation définitive au plus tard le 1er novembre 2026. Si l’événement n’est pas confirmé à cette date, est annulé ou reporté par ASCENSION, les participants peuvent choisir le remboursement intégral des paiements de programme ou un crédit intégral facultatif pour une future édition.",
      "Les participants qui annulent volontairement avant le début de leur programme peuvent demander un remboursement diminué de 10 % des paiements de programme reçus, lorsque la loi le permet, ou choisir un crédit intégral valable 24 mois pour une future édition. Toute différence de prix s’applique lors d’une nouvelle réservation. Les droits légaux d’annulation prévalent et aucun frais administratif ne sera déduit lorsqu’un remboursement intégral est exigé par la loi.",
      "Les demandes peuvent être envoyées par e-mail à ",
      "Les remboursements seront traités dans les 15 jours sur le moyen de paiement d’origine. Les crédits nécessitent l’accord du participant.",
      "Les vols, l’hébergement, les transferts et les services réservés séparément suivent les conditions de leurs fournisseurs. Attendez la confirmation écrite de l’événement avant de prendre des dispositions de voyage non remboursables.",
    ],
    quebecHeading: "Droits légaux d’annulation au Québec",
    quebec: "Pour les annulations admissibles de contrats conclus à distance en vertu du droit de la consommation du Québec, si le remboursement n’a pas été reçu dans les 15 jours suivant l’avis d’annulation, un participant ayant payé par carte de crédit peut demander une rétrofacturation dans les 60 jours suivants. L’émetteur doit accuser réception dans les 30 jours et créditer le compte dans le premier délai atteint entre 90 jours ou deux cycles de relevé complets. Si le délai applicable passe sans crédit, le consommateur peut envoyer une mise en demeure à l’émetteur. Les conditions d’admissibilité, les exceptions et les délais légaux s’appliquent.",
    quebecLinkLabel: "En savoir plus sur les droits d’annulation d’un achat en ligne au Québec",
    travelHeading: "Voyage et hébergement",
    travel: "L’hébergement, les vols et les transferts locaux ne sont pas inclus dans le prix du programme ASCENSION. Les participants choisissent et réservent leur propre hébergement, sauf indication expresse d’une offre confirmée.",
    wellnessHeading: "Expérience de bien-être et d’éducation",
    wellness: "ASCENSION est une expérience de bien-être et d’éducation, et non un service médical. Sa programmation ne remplace ni diagnostic, ni traitement, ni soins de santé professionnels. Chaque participant demeure responsable de décider si une activité lui convient et de consulter un professionnel de santé qualifié lorsque nécessaire.",
    faq: "ASCENSION Da Nang sera définitivement confirmé au plus tard le 1er novembre 2026. Si ASCENSION ne le confirme pas, annule ou reporte l’événement, choisissez le remboursement intégral des paiements de programme ou un crédit intégral pour une future édition. En cas d’annulation volontaire avant le début du programme, vous pouvez demander un remboursement diminué de 10 % lorsque la loi le permet ou un crédit intégral valable 24 mois; les droits légaux prévalent. Les remboursements sont traités dans les 15 jours. Consultez les Conditions pour la politique complète.",
    bookingSummary: "La confirmation définitive est prévue au plus tard le 1er novembre 2026. Consultez la politique d’annulation avant le paiement.",
    bookingTermsLabel: "Lire les conditions de réservation et d’annulation",
  },
  vi: {
    termsEyebrow: "Điều khoản",
    termsTitle: "Điều khoản rõ ràng trước khi đặt chỗ.",
    termsLead: "Các điều khoản này áp dụng cho ASCENSION SENSES · Đà Nẵng, 12–26 tháng 1 năm 2027.",
    attendanceLabel: "Xem lựa chọn tham dự",
    reservationHeading: "Đặt chỗ và thanh toán",
    reservation: "Khoản đặt cọc 300 USD giữ chỗ. Số dư chương trình đến hạn 30 ngày trước ngày 12 tháng 1 năm 2027.",
    cancellationHeading: "Chính sách hủy",
    cancellation: [
      "ASCENSION Đà Nẵng dự kiến diễn ra từ 12–26 tháng 1 năm 2027, với xác nhận cuối cùng chậm nhất vào ngày 1 tháng 11 năm 2026. Nếu sự kiện không được xác nhận trước thời hạn đó, bị ASCENSION hủy hoặc dời lịch, khách có thể chọn hoàn lại toàn bộ các khoản đã thanh toán cho chương trình hoặc tín dụng toàn giá trị tự chọn cho một kỳ sau.",
      "Khách tự nguyện hủy trước khi chương trình bắt đầu có thể yêu cầu hoàn tiền sau khi trừ 10% các khoản thanh toán chương trình đã nhận, khi pháp luật cho phép, hoặc chọn tín dụng toàn giá trị cho một kỳ sau trong vòng 24 tháng. Mọi chênh lệch giá sẽ áp dụng khi đặt lại. Quyền hủy theo luật định được ưu tiên và sẽ không trừ phí hành chính khi pháp luật yêu cầu hoàn tiền đầy đủ.",
      "Yêu cầu có thể gửi qua email đến ",
      "Khoản hoàn tiền sẽ được xử lý trong vòng 15 ngày về phương thức thanh toán ban đầu. Tín dụng cần có sự đồng ý của khách.",
      "Chuyến bay, chỗ ở, đưa đón và các dịch vụ đặt riêng tuân theo điều khoản của nhà cung cấp. Hãy chờ xác nhận bằng văn bản của sự kiện trước khi thực hiện các sắp xếp đi lại không hoàn tiền.",
    ],
    quebecHeading: "Quyền hủy theo luật định của Québec",
    quebec: "Đối với các trường hợp hủy hợp đồng từ xa đủ điều kiện theo luật bảo vệ người tiêu dùng Québec, nếu khoản hoàn tiền chưa được nhận trong vòng 15 ngày kể từ thông báo hủy, khách đã thanh toán bằng thẻ tín dụng có thể yêu cầu hoàn trả qua tổ chức phát hành trong 60 ngày tiếp theo. Tổ chức phát hành phải xác nhận đã nhận yêu cầu trong 30 ngày và ghi có tài khoản trong thời hạn sớm hơn giữa 90 ngày hoặc hai kỳ sao kê đầy đủ. Nếu thời hạn áp dụng trôi qua mà chưa được ghi có, người tiêu dùng có thể gửi thông báo chính thức cho tổ chức phát hành. Điều kiện áp dụng, ngoại lệ và thời hạn theo luật định vẫn có hiệu lực.",
    quebecLinkLabel: "Tìm hiểu về quyền hủy mua hàng trực tuyến tại Québec",
    travelHeading: "Đi lại và chỗ ở",
    travel: "Chỗ ở, chuyến bay và di chuyển địa phương không bao gồm trong giá chương trình ASCENSION. Khách tự chọn và đặt chỗ ở, trừ khi một ưu đãi đã xác nhận nêu rõ điều khác.",
    wellnessHeading: "Trải nghiệm sức khỏe và giáo dục",
    wellness: "ASCENSION là trải nghiệm chăm sóc sức khỏe và giáo dục, không phải chăm sóc y tế. Chương trình không thay thế chẩn đoán, điều trị hoặc chăm sóc y tế chuyên môn. Mỗi người tham gia tự chịu trách nhiệm quyết định hoạt động có phù hợp hay không và tìm tư vấn y tế có chuyên môn khi cần.",
    faq: "ASCENSION Đà Nẵng sẽ được xác nhận cuối cùng chậm nhất vào ngày 1 tháng 11 năm 2026. Nếu ASCENSION không xác nhận, hủy hoặc dời lịch sự kiện, bạn có thể chọn hoàn lại toàn bộ khoản thanh toán chương trình hoặc tín dụng toàn giá trị cho kỳ sau. Nếu tự hủy trước khi chương trình bắt đầu, bạn có thể yêu cầu hoàn tiền trừ 10% khi pháp luật cho phép hoặc tín dụng toàn giá trị trong 24 tháng; quyền theo luật định được ưu tiên. Hoàn tiền được xử lý trong 15 ngày. Xem Điều khoản để biết chính sách đầy đủ.",
    bookingSummary: "Xác nhận cuối cùng chậm nhất vào ngày 1 tháng 11 năm 2026. Hãy xem chính sách hủy trước khi thanh toán.",
    bookingTermsLabel: "Đọc điều khoản đặt chỗ và hủy",
  },
  ko: {
    termsEyebrow: "이용 조건",
    termsTitle: "예약 전 명확한 조건.",
    termsLead: "본 조건은 2027년 1월 12–26일 ASCENSION SENSES 다낭에 적용됩니다.",
    attendanceLabel: "참가 옵션 보기",
    reservationHeading: "예약과 결제",
    reservation: "300 USD 보증금으로 자리를 예약합니다. 프로그램 잔액은 2027년 1월 12일 30일 전까지 납부해야 합니다.",
    cancellationHeading: "취소 정책",
    cancellation: [
      "ASCENSION 다낭은 2027년 1월 12–26일에 예정되어 있으며, 최종 확정일은 2026년 11월 1일입니다. 해당 기한까지 행사가 확정되지 않거나 ASCENSION이 취소 또는 일정 변경을 하는 경우, 참가자는 프로그램 결제금 전액 환불 또는 향후 에디션에 사용할 수 있는 전액 크레딧 중 하나를 선택할 수 있습니다.",
      "프로그램 시작 전 자발적으로 취소하는 참가자는 법이 허용하는 경우 수령한 프로그램 결제금의 10%를 공제한 환불을 요청하거나, 24개월 이내 향후 에디션에 사용할 수 있는 전액 크레딧을 선택할 수 있습니다. 재예약 시 가격 차이가 적용됩니다. 법정 취소 권리는 우선하며, 법적으로 전액 환불이 필요한 경우 행정 수수료는 공제되지 않습니다.",
      "요청은 다음 이메일로 보낼 수 있습니다: ",
      "환불은 15일 이내에 원래 결제 수단으로 처리됩니다. 크레딧은 참가자의 동의가 필요합니다.",
      "항공편, 숙박, 교통 및 별도 예약 서비스에는 해당 공급업체의 조건이 적용됩니다. 환불 불가 여행을 예약하기 전에 서면 행사 확정을 기다려 주세요.",
    ],
    quebecHeading: "퀘벡 법정 취소 권리",
    quebec: "퀘벡 소비자법상 자격이 되는 원격계약 취소의 경우, 취소 통지 후 15일 이내에 환급을 받지 못한 신용카드 결제 고객은 그 후 60일 이내에 차지백을 요청할 수 있습니다. 발급기관은 30일 이내에 접수를 확인하고, 90일 또는 두 번의 완전한 명세서 기간 중 더 이른 시점까지 계정에 금액을 반영해야 합니다. 해당 기한이 지나도 반영되지 않으면 소비자는 발급기관에 공식 통지를 보낼 수 있습니다. 자격, 예외 및 법정 기한이 적용됩니다.",
    quebecLinkLabel: "퀘벡 온라인 구매 취소 권리 알아보기",
    travelHeading: "여행과 숙박",
    travel: "숙박, 항공편 및 현지 교통은 ASCENSION 프로그램 가격에 포함되지 않습니다. 확정된 제안에 별도로 명시되지 않는 한 참가자가 직접 숙박을 선택하고 예약합니다.",
    wellnessHeading: "웰니스 및 교육 경험",
    wellness: "ASCENSION은 의료 서비스가 아닌 웰니스 및 교육 경험입니다. 프로그램은 의학적 진단, 치료 또는 전문 의료를 대체하지 않습니다. 참가자는 활동의 적합성을 스스로 판단하고 필요한 경우 자격 있는 의료 전문가의 조언을 구할 책임이 있습니다.",
    faq: "ASCENSION 다낭은 2026년 11월 1일까지 최종 확정됩니다. ASCENSION이 확정하지 않거나 행사를 취소 또는 일정 변경하면 프로그램 결제금 전액 환불 또는 향후 에디션 전액 크레딧을 선택할 수 있습니다. 프로그램 시작 전 자발적으로 취소할 경우 법이 허용하는 범위에서 10%를 공제한 환불 또는 24개월 전액 크레딧을 요청할 수 있으며 법정 권리가 우선합니다. 환불은 15일 이내 처리됩니다. 전체 정책은 이용 조건을 확인해 주세요.",
    bookingSummary: "최종 확정일은 2026년 11월 1일입니다. 결제 전에 취소 정책을 확인해 주세요.",
    bookingTermsLabel: "예약 및 취소 조건 읽기",
  },
  "zh-hans": {
    termsEyebrow: "条款",
    termsTitle: "预订前了解清晰条款。",
    termsLead: "本条款适用于2027年1月12–26日ASCENSION SENSES岘港项目。",
    attendanceLabel: "查看参与选项",
    reservationHeading: "预订与付款",
    reservation: "支付300美元订金保留席位。项目余款须在2027年1月12日前30天付清。",
    cancellationHeading: "取消政策",
    cancellation: [
      "ASCENSION岘港项目计划于2027年1月12–26日举行，并将在2026年11月1日前最终确认。如活动未在该日期前确认、被ASCENSION取消或改期，参与者可选择全额退还项目付款，或选择用于未来一期的等值全额抵用额。",
      "在项目开始前自愿取消的参与者，在法律允许的情况下，可申请退还已收项目付款的90%，或选择24个月内用于未来一期的等值全额抵用额。重新预订时适用任何价差。法定取消权优先；法律要求全额退款时，不扣除管理费。",
      "申请可发送至：",
      "退款将在15天内退回原支付方式。抵用额须经参与者同意。",
      "航班、住宿、接送及单独预订的服务遵循各提供方自己的条款。在确认活动的书面通知前，请勿作出不可退款的旅行安排。",
    ],
    quebecHeading: "魁北克法定取消权利",
    quebec: "对于符合魁北克消费者法的远程合同取消，如在取消通知后15天内未收到退款，使用信用卡付款的参与者可在其后60天内申请拒付。发卡机构必须在30天内确认收悉，并在90天或两个完整账单周期中较早的期限内为账户入账。如适用期限届满仍未入账，消费者可向发卡机构发送正式通知。资格条件、例外和法定期限均适用。",
    quebecLinkLabel: "了解魁北克线上购买取消权利",
    travelHeading: "旅行与住宿",
    travel: "住宿、航班和当地交通不包含在ASCENSION项目价格中。除非已确认的方案明确说明，参与者自行选择并预订住宿。",
    wellnessHeading: "健康与教育体验",
    wellness: "ASCENSION是一项健康与教育体验，不属于医疗服务。项目内容不能替代医疗诊断、治疗或专业医疗服务。参与者有责任判断活动是否适合自己，并在需要时咨询合格的医疗专业人士。",
    faq: "ASCENSION岘港项目将在2026年11月1日前最终确认。如ASCENSION未确认、取消或改期，您可选择全额退还项目付款或获得未来一期的等值全额抵用额。若在项目开始前自愿取消，在法律允许的情况下可申请退还90%，或选择24个月有效的等值全额抵用额；法定权利优先。退款将在15天内处理。完整政策请见条款。",
    bookingSummary: "最终确认日为2026年11月1日。付款前请阅读取消政策。",
    bookingTermsLabel: "阅读预订与取消条款",
  },
};

export function getBookingPolicy(locale = "en") {
  return bookingPolicies[locale] || bookingPolicies.en;
}
