export const en = {
  language: "en",
  status: "approved",
  hero: {
    mobile: "Seven or fourteen days of Vietnamese wellness, movement, sound, food and creative renewal.",
    desktop: "A seven- or fourteen-day journey through Vietnamese wellness, movement, sound, food, culture and creativity—between the city, sea and mountains of Da Nang.",
  },
  introduction: {
    title: "Not a retreat from life. A return to it.",
    mobile: "Reconnect with your body. Discover Vietnamese traditions. Move, listen, taste, breathe and create—with the freedom to follow your own rhythm.",
    desktop: [
      "ASCENSION brings together Vietnamese traditional wellness, movement, sound, food, culture and creativity within one carefully curated experience.",
      "Follow a shared rhythm without losing your freedom. Participate in what serves you. Rest when you need to. Explore Da Nang and leave space for what surprises you.",
    ],
    progression: ["Arrive in the body.", "Open the senses.", "Experience the place.", "Return renewed."],
  },
  foundation: {
    eyebrow: "The foundation of ASCENSION",
    title: "One body. Everything connected.",
    mobile: "Diện Chẩn is a needle-free Vietnamese system combining reflexology, acupressure, heat, stretching and full-body therapeutic work. Every session responds to the individual—not a fixed routine.",
    desktop: "Diện Chẩn is the therapeutic foundation of ASCENSION—a distinctive Vietnamese system based on the understanding that the body is interconnected. Using needle-free acupressure, reflexology, heat, stretching and targeted bodywork, practitioners may work across the face, head, hands, feet, limbs and back. Each session responds to the individual rather than following a fixed routine.",
    details: [
      "The face may be the starting point. The whole body is the journey. Diện Chẩn often begins through reflex points across the face and head, but it is not limited to facial reflexology. The practitioner follows the body—working wherever attention is needed.",
      "A session may combine targeted pressure, specialized tools, therapeutic heat, stretching and full-body manual work. Hands. Feet. Head. Limbs. Back. Movement. Tension. Connection.",
      "No needles. No universal sequence. The treatment is adapted to the person.",
    ],
    disclaimer: "Diện Chẩn is presented as a traditional wellness practice and educational experience. Individual responses vary. Participation does not replace medical diagnosis, treatment or professional healthcare.",
  },
  widerProgram: {
    title: "One foundation. Many ways to return.",
    mobile: "Diện Chẩn is supported by movement, breath, guided meditation, sound baths, creative practice, food, culture and complementary wellness experiences.",
    desktop: "Diện Chẩn provides the therapeutic foundation. Around it, ASCENSION brings together movement, breath, guided meditation, sound baths, bodywork, creativity, food and cultural discovery. Participating facilitators will be announced as agreements are confirmed.",
  },
  sensoryStories: [
    {
      id: "embody",
      name: "EMBODY",
      title: "Feel more. Move more. Touch deeper.",
      mobile: "Reconnect with your body through Diện Chẩn, conscious movement and restorative touch. No pressure to perform. Begin where you are and listen to what your body has been waiting to tell you.",
      desktop: "Reconnect with your body through Diện Chẩn, conscious movement and restorative touch. Release tension. Restore awareness. Move without performance or pressure. Your body already knows the way. ASCENSION creates the space to listen.",
      cta: "Discover Diện Chẩn",
      href: "#dien-chan",
    },
    {
      id: "see",
      name: "SEE",
      title: "See differently.",
      mobile: "See the sea, the mountains and the lanterns of Hội An. Above all, see smiling faces, genuine hellos and the warmth of people who welcome you.",
      desktop: "See morning light across the sea, mountains beyond the city and lanterns illuminating Hội An. Above all, see people: smiling faces, genuine hellos and small gestures of generosity. Da Nang welcomes you before you even know its language.",
      cta: "Explore sight",
      details: "Marble Mountains is planned as a special excursion, with the day still to be confirmed. Other place-based moments remain illustrative until the final program is published.",
    },
    {
      id: "sound",
      name: "SOUND",
      title: "Listen deeply.",
      mobile: "Meditate with the waves. Enter guided meditation, music, sound baths and resonant sound. Rediscover the inner silence where peace begins.",
      desktop: "Meditate with the rhythm of the waves. Enter guided meditation, music, sound baths and immersive sound experiences. Feel vibration move through the body. Listen to the world around you—and to the stillness within.",
      cta: "Experience sound",
      details: "Sound baths and guided sound experiences are planned. Participating sound practitioners and session details will be announced as they are confirmed.",
    },
    {
      id: "taste",
      name: "TASTE",
      title: "Taste the place.",
      mobile: "Taste real food as nature designed it—fresh ingredients, prepared with care, shared tables and unforgettable Vietnamese dining experiences.",
      desktop: "Taste real food as nature designed it—fresh, alive and connected to the place from which it comes. Discover local markets, fragrant herbs, tropical fruit, coastal seafood and the balance of Vietnamese cuisine.",
      cta: "Discover taste",
      details: "The final culinary media and specific shared-meal schedule are pending. Only confirmed inclusions will appear in the participant program.",
    },
    {
      id: "breathe",
      name: "BREATHE",
      title: "Breathe all the way to your toes.",
      mobile: "Draw in the sea air. Discover how conscious breath can awaken presence, confidence, strength and movement.",
      desktop: "Draw in the sea air. Let the breath travel through the body, creating space for presence, confidence, strength and movement. A new year. A new cycle. In 2027, let the breath of life begin again.",
      cta: "Experience breath",
      details: "Breath-led experiences and participating facilitators will be announced only when confirmed.",
    },
    {
      id: "create",
      name: "CREATE · INTUITION",
      title: "Reconnect with the artist within.",
      quote: "“Every child is an artist. The problem is how to remain an artist once we grow up.” — Pablo Picasso",
      mobile: "Be present. Follow your intuition. Draw, paint, write, photograph, move—or create in whatever form calls to you.",
      desktop: "Creativity begins with presence. Notice what you feel. Trust your intuition. Allow something honest to emerge. Draw, paint, write, photograph, move or create in any form that calls to you. Nothing needs to be perfect. The practice is simply to begin.",
      cta: "Discover create",
      details: "Creative sessions are part of the ASCENSION Passport framework. Final media and the detailed materials schedule are still in production.",
    },
  ],
  ecstaticDance: {
    label: "ECSTATIC DANCE",
    title: "Move without being watched.",
    mobile: "No steps. No choreography. Follow the music, move in your own way and return to stillness.",
    desktop: [
      "No steps. No choreography. No performance.",
      "Follow the music from stillness into movement, energy and release—then return slowly to the body and the breath.",
      "Come alone or move with others. Participate in your own way.",
    ],
    status: "Planned ASCENSION experience · Facilitator to be announced",
    arc: [
      { label: "ARRIVE", copy: "Feel the ground and become present." },
      { label: "MOVE", copy: "Follow the rhythm without choreography or judgment." },
      { label: "RELEASE", copy: "Let movement, energy and breath unfold." },
      { label: "RETURN", copy: "Slow down, rest and listen to the body." },
    ],
  },
  participation: {
    eyebrow: "Your experience",
    title: "Free to participate. Free to choose.",
    copy: "ASCENSION invites participation without pressure. You do not need experience in movement, meditation, bodywork or creative practice. Every session begins with clear guidance, and you decide what feels appropriate for you.",
    principles: [
      "Come alone or come with someone.",
      "No previous experience is required.",
      "Participate in what serves you.",
      "Rest or step away when you need to.",
      "Consent is required before therapeutic touch.",
      "Choose whether you appear in photographs or video.",
      "Ask questions before any unfamiliar practice.",
    ],
  },
  host: {
    title: "Experienced before it was offered.",
    mobile: "Daniel Stanford experienced Diện Chẩn over several months in Da Nang, including 40 consecutive days of treatment. That personal journey became one of the foundations of ASCENSION.",
    desktop: "ASCENSION was not assembled from trends or online research. Daniel Stanford experienced Diện Chẩn over several months in Da Nang, including an intensive period of 40 consecutive days. The changes he personally observed in mobility, alignment and physical awareness became one of the foundations of this experience.",
    documentation: "Documentation from Daniel Stanford’s personal treatment history will explain why he chose to build Diện Chẩn into ASCENSION—not predict or guarantee results for participants.",
  },
  practitioner: {
    eyebrow: "Facilitate ASCENSION",
    title: "Bring your practice to Da Nang.",
    mobile: "Practitioner applications are open for the founding ASCENSION experience. We are inviting experienced facilitators in movement, breathwork, guided meditation, sound baths, bodywork, creativity and complementary wellness practices.",
    desktop: "ASCENSION is building a carefully selected circle of practitioners around its foundation in Diện Chẩn. Facilitators may contribute one experience, a short series, private appointments or a collaboration created specifically for Da Nang. Selection is based on experience, integrity, cultural fit and meaningful contribution to a small international group.",
  },
  finalCta: {
    mobile: "Seven or fourteen days. One intimate experience. A different way to encounter Vietnam—and yourself.",
    desktop: "Come for seven days or experience the complete fourteen-day journey. Discover Vietnamese knowledge. Reconnect with your body. Share extraordinary food, sound, movement, culture and creative experience within a small, carefully curated group.",
  },
};

export const passportCategories = [
  { name: "FOUNDATION", copy: "Diện Chẩn as the signature traditional wellness and educational experience." },
  { name: "MOVE", copy: "Curated group movement, breathwork and embodied practices, including planned Ecstatic Dance." },
  { name: "RESTORE", copy: "Selected group restoration and wellness experiences, with private treatments identified separately." },
  { name: "SOUND", copy: "Planned guided meditation, sound baths and sensory listening experiences." },
  { name: "TASTE", copy: "Selected shared culinary experiences connecting guests with Da Nang through food." },
  { name: "DISCOVER", copy: "Curated cultural and place-based experiences across Da Nang and its surroundings." },
  { name: "CREATE", copy: "Photography, drawing, painting, collage and material exploration." },
];

export const faqItems = [
  ["What is ASCENSION?", "A curated 7- or 14-day experience connecting Vietnamese wellness, movement, sound, food, culture and creativity in Da Nang."],
  ["What is Diện Chẩn?", "A modern Vietnamese, needle-free system rooted in traditional principles and combining reflexology, acupressure, heat, stretching and full-body therapeutic work."],
  ["Does Diện Chẩn use needles?", "No. Diện Chẩn is needle-free."],
  ["Do I need experience with movement or meditation?", "No previous experience is required. Guidance is provided and you decide what feels appropriate."],
  ["Can I attend alone?", "Yes. You may come alone or with someone."],
  ["Must I participate in every session?", "No. Participate in what serves you, and rest or step away when you need to."],
  ["What is included in the program price?", "The price covers access to confirmed shared ASCENSION programming and the participant cohort. Final inclusions will be stated clearly before booking."],
  ["Are accommodation and flights included?", "No. Guests select and book their own accommodation, flights and local transfers."],
  ["What is the difference between 7 and 14 days?", "The 7-day program runs January 12–19 for USD $1,200. The complete 14-day program runs January 12–26 for USD $2,000."],
  ["Will Ecstatic Dance be included?", "Ecstatic Dance is planned as part of the EMBODY experience. The facilitator, location and final schedule will be announced after confirmation."],
  ["Will sound baths be included?", "Sound baths and guided sound experiences are part of the intended program. Participating sound practitioners and session details will be announced as they are confirmed."],
  ["Who are the facilitators?", "Participating facilitators will be announced as agreements are confirmed. ASCENSION is selecting practitioners for experience, integrity and alignment with the program."],
  ["Can I choose whether I am photographed?", "Yes. You choose whether you appear in photographs or video."],
  ["What if I have an injury or medical condition?", "Ask questions before participating and consult an appropriate healthcare professional when needed. ASCENSION experiences do not replace medical diagnosis or treatment."],
  ["How do I reserve my place?", "Use a clearly labelled Reserve Your Place link. The current checkout requests a USD $300 deposit, subject to final commercial verification."],
  ["Can I apply as a practitioner?", "Yes. Practitioner applications are open through the prefilled application email below."],
];
