const shared = {
  fr: {
    language:"fr", hero:{mobile:"Sept ou quatorze jours de bien-être vietnamien, mouvement, son, gastronomie et renouveau créatif.",desktop:"Un voyage de sept ou quatorze jours à travers le bien-être, le mouvement, le son, la gastronomie, la culture et la créativité du Vietnam—entre ville, mer et montagnes de Da Nang."},
    introduction:{title:"Pas une retraite loin de la vie. Un retour à elle.",mobile:"Retrouvez votre corps. Découvrez les traditions vietnamiennes. Bougez, écoutez, goûtez, respirez et créez—libre de suivre votre propre rythme.",desktop:["ASCENSION réunit le bien-être traditionnel vietnamien, le mouvement, le son, la gastronomie, la culture et la créativité dans une expérience soigneusement conçue.","Suivez un rythme commun sans perdre votre liberté. Participez à ce qui vous fait du bien. Reposez-vous quand vous en avez besoin. Explorez Da Nang et laissez place à l’inattendu."],progression:["Arriver dans le corps.","Ouvrir les sens.","Vivre le lieu.","Revenir renouvelé."]},
    foundation:{eyebrow:"Le fondement d’ASCENSION",title:"Un seul corps. Tout est lié.",mobile:"Le Diện Chẩn est une méthode vietnamienne sans aiguilles associant réflexologie, acupression, chaleur, étirements et travail thérapeutique du corps entier. Chaque séance s’adapte à la personne—jamais à une routine fixe.",desktop:"Le Diện Chẩn est le fondement thérapeutique d’ASCENSION—une méthode vietnamienne distinctive fondée sur l’interconnexion du corps. Par l’acupression sans aiguilles, la réflexologie, la chaleur, les étirements et un travail corporel ciblé, la pratique peut porter sur le visage, la tête, les mains, les pieds, les membres et le dos. Chaque séance répond à la personne plutôt qu’à une routine fixe.",leader:"Les séances quotidiennes sont dirigées par la Dre Huỳnh Bảo Loan, à Da Nang.",details:["Le visage peut être le point de départ. Le corps entier est le voyage. Le Diện Chẩn commence souvent par des points réflexes du visage et de la tête, sans se limiter à la réflexologie faciale.","Une séance peut réunir pression ciblée, outils spécialisés, chaleur thérapeutique, étirements et travail manuel du corps entier.","Sans aiguilles. Sans séquence universelle. Le soin s’adapte à la personne."],disclaimer:"Le Diện Chẩn est présenté comme une pratique traditionnelle de bien-être et une expérience éducative. Les réactions individuelles varient. Il ne remplace ni diagnostic, ni traitement, ni soins médicaux professionnels."},
    widerProgram:{title:"Un fondement. Plusieurs chemins de retour.",mobile:"Le Diện Chẩn est accompagné de mouvement, respiration, méditation guidée, bains sonores, création, gastronomie, culture et pratiques complémentaires.",desktop:"Le Diện Chẩn constitue le fondement thérapeutique. Autour de lui, ASCENSION réunit mouvement, respiration, méditation guidée, bains sonores, travail corporel, créativité, gastronomie et découverte culturelle. Les intervenants seront annoncés à mesure que les accords seront confirmés."},
    sensoryStories:[
      {id:"embody",name:"INCARNER",title:"Ressentir plus. Bouger plus. Toucher plus profondément.",keywords:"ACUPRESSION · TRAVAIL CORPOREL · MOUVEMENT",mobile:"Retrouvez votre corps grâce au Diện Chẩn, au mouvement conscient et au toucher réparateur. Aucune pression de performance. Commencez là où vous êtes.",desktop:"Retrouvez votre corps grâce au Diện Chẩn, au mouvement conscient et au toucher réparateur. Libérez les tensions. Retrouvez la conscience. Bougez sans performance ni pression. Votre corps connaît déjà le chemin.",cta:"Découvrir le Diện Chẩn",href:"/dien-chan"},
      {id:"see",name:"VOIR",title:"Voir autrement.",keywords:"MER · MONTAGNES · HỘI AN · VISAGES",mobile:"Voyez la mer, les montagnes et les lanternes de Hội An. Surtout, voyez les sourires, les bonjours sincères et la chaleur de ceux qui vous accueillent.",desktop:"Voyez la lumière du matin sur la mer, les montagnes derrière la ville et les lanternes de Hội An. Surtout, voyez les gens : sourires, bonjours sincères et petits gestes de générosité.",cta:"Explorer la vue",details:"Les Montagnes de Marbre sont prévues comme excursion spéciale, sous réserve de confirmation. Les autres moments liés au lieu restent indicatifs jusqu’à la publication du programme final."},
      {id:"sound",name:"SON",title:"Écouter profondément.",keywords:"VAGUES · MUSIQUE · BAINS SONORES · SILENCE",mobile:"Méditez au rythme des vagues. Entrez dans la méditation guidée, la musique, les bains sonores et retrouvez le silence intérieur.",desktop:"Méditez au rythme des vagues. Découvrez méditation guidée, musique, bains sonores et expériences immersives. Sentez la vibration traverser le corps. Écoutez le monde—et le silence intérieur.",cta:"Vivre le son",details:"Des bains sonores et expériences guidées sont prévus. Les praticiens et détails seront annoncés après confirmation."},
      {id:"taste",name:"GOÛTER",title:"Goûter le lieu.",keywords:"TABLE PARTAGÉE · SAVEURS LOCALES",mobile:"Goûtez une cuisine vraie—ingrédients frais, préparés avec soin, tables partagées et expériences vietnamiennes mémorables.",desktop:"Goûtez une cuisine fraîche, vivante et liée à son territoire. Découvrez marchés locaux, herbes parfumées, fruits tropicaux, produits de la mer et l’équilibre de la cuisine vietnamienne.",cta:"Découvrir le goût",details:"Les repas partagés et horaires précis ne seront publiés qu’après confirmation."},
      {id:"breathe",name:"RESPIRER",title:"Respirer jusqu’au bout des orteils.",keywords:"AIR SALIN · TERRE CHAUDE",mobile:"Inspirez l’air marin. Découvrez comment une respiration consciente réveille présence, confiance, force et mouvement.",desktop:"Inspirez l’air marin. Laissez le souffle parcourir le corps et créer de l’espace pour la présence, la confiance, la force et le mouvement. En 2027, laissez la vie recommencer à respirer.",cta:"Vivre le souffle",details:"Les expériences de respiration et leurs intervenants seront annoncés seulement après confirmation."},
      {id:"create",name:"CRÉER",title:"Retrouver l’artiste en soi.",keywords:"INTUITION · DESSIN · PEINTURE · ÉCRITURE · PHOTO",quote:"« Chaque enfant est un artiste. Le problème est de rester un artiste une fois devenu adulte. » — Pablo Picasso",mobile:"Soyez présent. Suivez votre intuition. Dessinez, peignez, écrivez, photographiez, bougez—ou créez sous la forme qui vous appelle.",desktop:"La créativité commence par la présence. Remarquez ce que vous ressentez. Faites confiance à votre intuition. Laissez émerger quelque chose de sincère. Rien n’a besoin d’être parfait. Il suffit de commencer.",cta:"Découvrir la création",details:"Les séances créatives font partie du Passeport ASCENSION. Les formats et matériaux confirmés seront indiqués dans le programme."}
    ],
    ecstaticDance:{label:"DANSE LIBRE",title:"Bouger sans être observé.",mobile:"Pas de pas. Pas de chorégraphie. Suivez la musique, bougez à votre manière et revenez au calme.",desktop:["Pas de pas. Pas de chorégraphie. Pas de performance.","Suivez la musique du calme au mouvement, à l’énergie et au lâcher-prise—puis revenez lentement au corps et au souffle.","Venez seul ou bougez avec les autres. Participez à votre façon."],status:"Expérience ASCENSION prévue · Intervenant à annoncer",arc:[{label:"ARRIVER",copy:"Sentir le sol et devenir présent."},{label:"BOUGER",copy:"Suivre le rythme sans chorégraphie ni jugement."},{label:"LIBÉRER",copy:"Laisser se déployer mouvement, énergie et souffle."},{label:"REVENIR",copy:"Ralentir, se reposer et écouter le corps."}]},
    participation:{eyebrow:"Votre expérience",title:"Libre de participer. Libre de choisir.",copy:"ASCENSION invite sans pression. Aucune expérience en mouvement, méditation, travail corporel ou création n’est requise. Chaque séance commence par des indications claires; vous décidez ce qui vous convient.",principles:["Venir seul ou accompagné.","Aucune expérience préalable requise.","Participer à ce qui vous fait du bien.","Se reposer ou s’éloigner au besoin.","Le consentement précède tout toucher thérapeutique.","Choisir d’apparaître ou non en photo ou vidéo.","Poser des questions avant toute pratique inconnue."]},
    practitioner:{eyebrow:"Animer ASCENSION",title:"Apportez votre pratique à Da Nang.",mobile:"Les candidatures sont ouvertes pour l’édition fondatrice. Nous invitons des intervenants expérimentés en mouvement, respiration, méditation, son, travail corporel, créativité et bien-être complémentaire.",desktop:"ASCENSION constitue un cercle soigneusement choisi autour du Diện Chẩn. Un intervenant peut proposer une expérience, une courte série, des rendez-vous privés ou une collaboration conçue pour Da Nang. La sélection repose sur l’expérience, l’intégrité, l’adéquation culturelle et la contribution à un petit groupe international."},
    finalCta:{mobile:"Sept ou quatorze jours. Une expérience intime. Une autre façon de rencontrer le Vietnam—et vous-même.",desktop:"Venez sept jours ou vivez le parcours complet de quatorze jours. Découvrez les savoirs vietnamiens. Retrouvez votre corps. Partagez gastronomie, son, mouvement, culture et création dans un petit groupe soigneusement choisi."}
  },
  ko: {
    language:"ko", hero:{mobile:"베트남 웰니스, 움직임, 소리, 음식과 창조적 회복을 만나는 7일 또는 14일.",desktop:"다낭의 도시와 바다, 산 사이에서 베트남 웰니스, 움직임, 소리, 음식, 문화와 창조성을 경험하는 7일 또는 14일의 여정입니다."},
    introduction:{title:"삶을 떠나는 휴식이 아니라, 삶으로 돌아오는 여정.",mobile:"몸과 다시 연결되고 베트남의 전통을 만나세요. 자신만의 리듬으로 움직이고, 듣고, 맛보고, 숨 쉬고, 창조하세요.",desktop:["ASCENSION은 베트남 전통 웰니스, 움직임, 소리, 음식, 문화와 창조성을 하나의 세심하게 큐레이션된 경험으로 엮습니다.","공동의 리듬을 따르되 자유를 잃지 마세요. 필요한 것에 참여하고, 필요할 때 쉬며, 다낭을 탐험하고 예상치 못한 순간을 위한 여백을 남기세요."],progression:["몸에 도착합니다.","감각을 엽니다.","장소를 경험합니다.","새로워져 돌아갑니다."]},
    foundation:{eyebrow:"ASCENSION의 토대",title:"하나의 몸. 모든 것은 연결되어 있습니다.",mobile:"디엔쩐(Diện Chẩn)은 반사요법, 지압, 온열, 스트레칭과 전신 테라피를 결합한 베트남의 비침습적 웰니스 체계입니다. 모든 세션은 정해진 순서가 아니라 개인에게 맞춰집니다.",desktop:"디엔쩐은 ASCENSION의 치료적 토대입니다. 몸 전체가 서로 연결되어 있다는 이해를 바탕으로 한 독특한 베트남 방식으로, 바늘 없는 지압, 반사요법, 온열, 스트레칭과 목표 지향적 바디워크를 얼굴, 머리, 손, 발, 팔다리와 등에 적용할 수 있습니다. 각 세션은 고정된 루틴이 아닌 개인에게 맞춰집니다.",leader:"매일 디엔쩐 세션은 다낭의 Huỳnh Bảo Loan 박사가 진행합니다.",details:["얼굴은 시작점일 수 있지만, 여정은 온몸으로 이어집니다. 디엔쩐은 얼굴과 머리의 반사점에서 시작하더라도 얼굴 반사요법에만 머물지 않습니다.","세션은 목표 지압, 전문 도구, 치료적 온열, 스트레칭과 전신 수기 작업을 결합할 수 있습니다.","바늘 없이. 획일적인 순서 없이. 개인에게 맞춘 방식으로."],disclaimer:"디엔쩐은 전통 웰니스 실천이자 교육적 경험으로 소개됩니다. 개인의 반응은 다를 수 있으며 의료 진단, 치료 또는 전문 의료를 대체하지 않습니다."},
    widerProgram:{title:"하나의 토대. 돌아오는 여러 길.",mobile:"디엔쩐을 중심으로 움직임, 호흡, 가이드 명상, 사운드 배스, 창작, 음식, 문화와 보완적 웰니스 경험이 이어집니다.",desktop:"디엔쩐이 치료적 토대를 이룹니다. 그 주위에 움직임, 호흡, 가이드 명상, 사운드 배스, 바디워크, 창조성, 음식과 문화 탐험이 모입니다. 참여 진행자는 계약이 확정되는 대로 발표됩니다."},
    sensoryStories:[
      {id:"embody",name:"몸",title:"더 느끼고. 더 움직이고. 더 깊이 닿기.",keywords:"지압 · 바디워크 · 움직임",mobile:"디엔쩐, 의식적인 움직임과 회복의 터치를 통해 몸과 다시 연결하세요. 수행해야 한다는 압박 없이 지금 여기서 시작하세요.",desktop:"디엔쩐, 의식적인 움직임과 회복의 터치를 통해 몸과 다시 연결하세요. 긴장을 풀고 감각을 회복하세요. 몸은 이미 길을 알고 있으며 ASCENSION은 듣기 위한 공간을 만듭니다.",cta:"디엔쩐 알아보기",href:"/dien-chan"},
      {id:"see",name:"보다",title:"다르게 보기.",keywords:"바다 · 산 · 호이안 · 사람들",mobile:"바다와 산, 호이안의 등불을 바라보세요. 무엇보다 미소와 진심 어린 인사, 당신을 맞이하는 사람들의 온기를 만나세요.",desktop:"바다 위 아침빛, 도시 너머의 산과 호이안의 등불을 보세요. 무엇보다 사람들의 미소, 진심 어린 인사와 작은 친절을 발견하세요.",cta:"시각 경험하기",details:"오행산은 특별 일정으로 계획되어 있으며 날짜는 아직 확정되지 않았습니다. 다른 장소 기반 경험은 최종 프로그램 공개 전까지 예시입니다."},
      {id:"sound",name:"소리",title:"깊이 듣기.",keywords:"파도 · 음악 · 사운드 배스 · 고요",mobile:"파도의 리듬과 함께 명상하세요. 가이드 명상, 음악, 사운드 배스를 통해 내면의 고요를 다시 발견하세요.",desktop:"파도의 리듬과 함께 명상하세요. 가이드 명상, 음악, 사운드 배스와 몰입형 소리를 경험하고 진동이 몸을 지나가는 것을 느껴보세요.",cta:"소리 경험하기",details:"사운드 배스와 가이드 사운드 경험은 계획 중입니다. 진행자와 세부 일정은 확정 후 발표됩니다."},
      {id:"taste",name:"맛",title:"장소를 맛보기.",keywords:"함께하는 식탁 · 현지의 맛",mobile:"신선한 재료와 정성, 함께하는 식탁으로 기억에 남을 베트남 음식을 맛보세요.",desktop:"그 장소에서 태어난 신선하고 생기 있는 음식을 맛보세요. 현지 시장, 향긋한 허브, 열대 과일, 해산물과 베트남 요리의 균형을 발견하세요.",cta:"미각 경험하기",details:"공동 식사의 구체적인 포함 사항과 시간은 확정 후 공개됩니다."},
      {id:"breathe",name:"숨",title:"발끝까지 숨 쉬기.",keywords:"소금기 어린 공기 · 따뜻한 땅",mobile:"바닷바람을 들이마시고 의식적인 호흡이 현존, 자신감, 힘과 움직임을 깨우는 방식을 발견하세요.",desktop:"바닷바람을 들이마시고 호흡이 온몸을 흐르게 하세요. 현존, 자신감, 힘과 움직임을 위한 공간이 열립니다. 2027년, 생명의 숨을 다시 시작하세요.",cta:"호흡 경험하기",details:"호흡 경험과 참여 진행자는 확정된 뒤 발표됩니다."},
      {id:"create",name:"창조",title:"내면의 예술가와 다시 만나기.",keywords:"직관 · 드로잉 · 회화 · 글쓰기 · 사진",quote:"“모든 아이는 예술가다. 문제는 어른이 되어서도 예술가로 남는 것이다.” — 파블로 피카소",mobile:"현재에 머물고 직관을 따르세요. 그리고, 쓰고, 촬영하고, 움직이거나 마음이 이끄는 방식으로 창조하세요.",desktop:"창조성은 현존에서 시작됩니다. 느끼는 것을 알아차리고 직관을 믿으세요. 완벽할 필요는 없습니다. 그저 시작하는 것이 연습입니다.",cta:"창조 경험하기",details:"창작 세션은 ASCENSION 패스포트의 일부입니다. 확정된 형식과 재료는 참가자 프로그램에 명시됩니다."}
    ],
    ecstaticDance:{label:"엑스타틱 댄스",title:"시선에서 자유롭게 움직이기.",mobile:"정해진 스텝도, 안무도 없습니다. 음악을 따라 자신만의 방식으로 움직이고 고요로 돌아오세요.",desktop:["정해진 스텝도, 안무도, 공연도 없습니다.","고요에서 움직임과 에너지, 해방으로 음악을 따라가고 천천히 몸과 호흡으로 돌아오세요.","혼자 오거나 함께 움직이세요. 자신만의 방식으로 참여하세요."],status:"계획 중인 ASCENSION 경험 · 진행자 추후 발표",arc:[{label:"도착",copy:"바닥을 느끼고 현재에 머뭅니다."},{label:"움직임",copy:"안무나 판단 없이 리듬을 따릅니다."},{label:"해방",copy:"움직임, 에너지와 호흡이 펼쳐지게 둡니다."},{label:"귀환",copy:"천천히 쉬며 몸의 소리를 듣습니다."}]},
    participation:{eyebrow:"당신의 경험",title:"참여할 자유. 선택할 자유.",copy:"ASCENSION은 압박 없는 참여를 제안합니다. 움직임, 명상, 바디워크나 창작 경험이 없어도 됩니다. 각 세션은 명확한 안내로 시작되며 무엇이 적합한지는 스스로 결정합니다.",principles:["혼자 또는 함께 오세요.","사전 경험은 필요하지 않습니다.","도움이 되는 것에 참여하세요.","필요할 때 쉬거나 자리를 비우세요.","치료적 터치 전에는 동의가 필요합니다.","사진이나 영상 출연 여부를 선택하세요.","낯선 실천 전에는 질문하세요."]},
    practitioner:{eyebrow:"ASCENSION 진행",title:"당신의 실천을 다낭으로 가져오세요.",mobile:"첫 ASCENSION을 위한 진행자 지원을 받습니다. 움직임, 호흡, 명상, 사운드, 바디워크, 창작과 보완 웰니스 분야의 경험 있는 실천가를 초대합니다.",desktop:"ASCENSION은 디엔쩐을 중심으로 신중하게 선정된 실천가 그룹을 만듭니다. 하나의 경험, 짧은 시리즈, 개인 세션 또는 다낭을 위해 만든 협업을 제안할 수 있습니다. 경험, 진정성, 문화적 적합성과 작은 국제 그룹에 대한 의미 있는 기여를 기준으로 선정합니다."},
    finalCta:{mobile:"7일 또는 14일. 친밀한 하나의 경험. 베트남과 자신을 새롭게 만나는 방식.",desktop:"7일간 함께하거나 14일 전체 여정을 경험하세요. 베트남의 지혜를 발견하고 몸과 다시 연결되며, 작은 큐레이션 그룹 안에서 음식, 소리, 움직임, 문화와 창조성을 나누세요."}
  },
  "zh-hans": {
    language:"zh-hans", hero:{mobile:"七天或十四天，体验越南疗愈、运动、声音、美食与创造力的焕新。",desktop:"在岘港的城市、海洋与群山之间，展开一场七天或十四天的越南疗愈、运动、声音、美食、文化与创造力之旅。"},
    introduction:{title:"不是逃离生活，而是回归生活。",mobile:"重新连接身体，发现越南传统。按照自己的节奏去运动、聆听、品味、呼吸与创造。",desktop:["ASCENSION将越南传统疗愈、运动、声音、美食、文化与创造力汇聚成一场精心策划的体验。","跟随共同节奏，同时保留自由。参加对你有益的活动，需要时休息，探索岘港，并为意外惊喜留出空间。"],progression:["回到身体。","打开感官。","感受此地。","焕新归来。"]},
    foundation:{eyebrow:"ASCENSION的核心",title:"一个身体，万物相连。",mobile:"面诊（Diện Chẩn）是一种不用针的越南方法，结合反射疗法、指压、热疗、拉伸与全身理疗。每次体验都根据个人调整，而非固定流程。",desktop:"面诊是ASCENSION的疗愈基础。这一独特的越南体系建立在身体彼此相连的理解之上，通过无针指压、反射疗法、热疗、拉伸与针对性身体工作，可作用于面部、头部、手、足、四肢和背部。每次体验回应个人需要，而非遵循固定流程。",leader:"每日面诊由岘港的Huỳnh Bảo Loan医生带领。",details:["面部可能是起点，全身才是旅程。面诊常从面部和头部的反射点开始，但并不局限于面部反射疗法。","体验可结合针对性按压、专用工具、治疗性热疗、拉伸和全身手法。","不用针。没有统一流程。根据每个人调整。"],disclaimer:"面诊作为传统健康实践与教育体验呈现。个人反应可能不同，不能替代医疗诊断、治疗或专业医疗服务。"},
    widerProgram:{title:"一个核心，多种回归方式。",mobile:"围绕面诊，还有运动、呼吸、引导冥想、声音浴、创造、美食、文化与补充性疗愈体验。",desktop:"面诊构成疗愈基础。围绕它，ASCENSION汇聚运动、呼吸、引导冥想、声音浴、身体工作、创造力、美食与文化探索。参与导师将在合作确认后公布。"},
    sensoryStories:[
      {id:"embody",name:"身体",title:"感受更多。运动更多。触碰更深。",keywords:"指压 · 身体疗愈 · 运动",mobile:"通过面诊、有意识的运动和修复性触碰重新连接身体。无需表现，从当下开始，聆听身体。",desktop:"通过面诊、有意识的运动和修复性触碰重新连接身体。释放紧张，恢复觉察，不为表现，也没有压力。你的身体已经知道方向。",cta:"了解面诊",href:"/dien-chan"},
      {id:"see",name:"看见",title:"以不同方式看见。",keywords:"海洋 · 群山 · 会安 · 人们",mobile:"看海、看山、看会安灯笼。更重要的是，看见笑容、真诚问候与欢迎你的温暖。",desktop:"看晨光洒过海面、城市之后的群山和点亮会安的灯笼。更重要的是看见人：笑脸、真诚的问候与细微的善意。",cta:"探索视觉",details:"五行山计划作为特别游览，日期尚待确认。其他地点体验在最终计划发布前仅作示意。"},
      {id:"sound",name:"声音",title:"深入聆听。",keywords:"海浪 · 音乐 · 声音浴 · 宁静",mobile:"伴随海浪冥想。进入引导冥想、音乐和声音浴，重新发现内在宁静。",desktop:"伴随海浪节奏冥想。进入引导冥想、音乐、声音浴与沉浸式声音体验。感受振动穿过身体，聆听周围世界与内心的宁静。",cta:"体验声音",details:"声音浴与引导声音体验正在计划中。参与导师和细节将在确认后公布。"},
      {id:"taste",name:"品味",title:"品味此地。",keywords:"共享餐桌 · 当地风味",mobile:"品尝自然本真的食物——新鲜食材、用心烹制、共享餐桌和难忘的越南饮食体验。",desktop:"品尝新鲜、有生命力并与土地相连的食物。探索当地市场、香草、热带水果、海鲜和越南料理的平衡。",cta:"探索味觉",details:"共享餐食的具体内容和时间将在确认后公布。"},
      {id:"breathe",name:"呼吸",title:"让呼吸抵达脚趾。",keywords:"咸湿空气 · 温暖大地",mobile:"吸入海风，感受有意识的呼吸如何唤醒临在、自信、力量和运动。",desktop:"吸入海风，让呼吸穿过身体，为临在、自信、力量和运动创造空间。新的一年，新的循环。2027年，让生命重新呼吸。",cta:"体验呼吸",details:"呼吸体验及导师仅在确认后公布。"},
      {id:"create",name:"创造",title:"重新连接内在艺术家。",keywords:"直觉 · 绘画 · 写作 · 摄影",quote:"“每个孩子都是艺术家，问题是长大后如何继续做艺术家。”——巴勃罗·毕加索",mobile:"活在当下，跟随直觉。绘画、写作、摄影、运动，或以任何召唤你的方式创造。",desktop:"创造力始于临在。觉察你的感受，相信直觉，让真实自然浮现。无需完美，练习只是开始。",cta:"探索创造",details:"创作环节属于ASCENSION护照体系。确认后的形式与材料将在参与者计划中说明。"}
    ],
    ecstaticDance:{label:"自由舞动",title:"不被注视地移动。",mobile:"没有规定动作，没有编舞。跟随音乐，以自己的方式移动，然后回归宁静。",desktop:["没有规定动作，没有编舞，也没有表演。","跟随音乐，从静止进入运动、能量与释放，再慢慢回到身体和呼吸。","独自前来或与他人共舞，以自己的方式参与。"],status:"计划中的ASCENSION体验 · 导师待公布",arc:[{label:"抵达",copy:"感受地面，回到当下。"},{label:"移动",copy:"不带编舞与评判地跟随节奏。"},{label:"释放",copy:"让运动、能量与呼吸自然展开。"},{label:"回归",copy:"慢下来，休息并聆听身体。"}]},
    participation:{eyebrow:"你的体验",title:"自由参与，自由选择。",copy:"ASCENSION邀请你在没有压力的情况下参与。无需运动、冥想、身体工作或创作经验。每次活动都有清晰指导，由你决定什么适合自己。",principles:["独自或结伴前来。","无需任何经验。","参与对你有益的内容。","需要时休息或离开。","治疗性触碰前必须获得同意。","自行选择是否出现在照片或视频中。","对陌生实践先提出问题。"]},
    practitioner:{eyebrow:"参与带领ASCENSION",title:"把你的实践带到岘港。",mobile:"首届ASCENSION正在接受导师申请。我们邀请在运动、呼吸、引导冥想、声音、身体工作、创造与补充疗愈方面有经验的实践者。",desktop:"ASCENSION正围绕面诊建立一个精心选择的实践者团队。导师可贡献一次体验、短系列、私人预约或为岘港特别设计的合作。选择基于经验、诚信、文化契合度及对小型国际团体的实际贡献。"},
    finalCta:{mobile:"七天或十四天。一场亲密体验。以不同方式遇见越南，也遇见自己。",desktop:"选择七天，或体验完整的十四天旅程。发现越南知识，重新连接身体，在精心选择的小型团体中分享美食、声音、运动、文化与创造。"}
  }
};

export const translatedContent = shared;

export const translatedUi = {
  fr:{nav:{experience:"Expérience",about:"À propos",attend:"Participer",facilitate:"Animer",menu:"Menu",close:"Fermer"},reserve:"Réserver votre place",ask:"Poser une question",embody:"L’incarner",explore:"Explorer l’expérience",day:"JOUR",dusk:"CRÉPUSCULE",slogan:["Guérir l’âme.","Réveiller les sens."],place:"Da Nang, Vietnam",dates:"12–26 janvier 2027",series:"UNE SÉRIE MODUS",glanceTitle:"Da Nang,\nVietnam",glanceSub:"L’expérience,\nen bref.",glanceLead:"Choisissez sept jours ou les quatorze jours complets entre ville, mer et montagne.",seven:"7 jours",fourteen:"14 jours",small:"Petit groupe intime. Hébergement et transport séparés.",compare:"Comparer 7 et 14 jours",included:"Voir ce qui est inclus",entity:"ASCENSION est une expérience immersive de bien-être et de culture de sept ou quatorze jours à Da Nang, au Vietnam, du 12 au 26 janvier 2027, fondée sur le Diện Chẩn, méthode vietnamienne sans aiguilles.",sixWays:"Six chemins vers\nle présent.",passport:"Votre Passeport ASCENSION",experienceRhythm:"Votre expérience.\nVotre rythme.",curatedFreedom:"Suivez un programme conçu sans perdre votre liberté.",passportBody:"Votre Passeport ASCENSION ouvre les expériences communes confirmées tout en laissant du temps pour se reposer, explorer Da Nang et choisir des séances privées.",faqKicker:"Avant votre arrivée",faqTitle:"Vos questions,\nnos réponses.",facilitator:"Intervenants",apply:"Proposer votre pratique"},
  ko:{nav:{experience:"경험",about:"소개",attend:"참가",facilitate:"진행",menu:"메뉴",close:"닫기"},reserve:"자리 예약",ask:"문의하기",embody:"몸으로 느끼기",explore:"경험 둘러보기",day:"낮",dusk:"해질녘",slogan:["영혼을 치유하세요.","감각을 되살리세요."],place:"베트남 다낭",dates:"2027년 1월 12–26일",series:"MODUS 시리즈",glanceTitle:"다낭,\n베트남",glanceSub:"경험을\n한눈에.",glanceLead:"도시와 바다, 산 사이에서 7일 또는 14일 전체 여정을 선택하세요.",seven:"7일",fourteen:"14일",small:"작고 친밀한 그룹. 숙박과 교통은 별도입니다.",compare:"7일과 14일 비교",included:"포함 사항 보기",entity:"ASCENSION은 2027년 1월 12일부터 26일까지 베트남 다낭에서 열리는 7일 또는 14일의 몰입형 웰니스·문화 경험으로, 바늘을 사용하지 않는 베트남 디엔쩐을 중심으로 합니다.",sixWays:"현재로 들어가는\n여섯 가지 길.",passport:"당신의 ASCENSION 패스포트",experienceRhythm:"당신의 경험.\n당신의 리듬.",curatedFreedom:"자유를 잃지 않고 큐레이션된 프로그램을 따르세요.",passportBody:"ASCENSION 패스포트는 확정된 공동 경험을 열어주면서 휴식, 다낭 탐험과 선택형 개인 세션을 위한 여백을 남깁니다.",faqKicker:"도착하기 전에",faqTitle:"질문과\n답변.",facilitator:"진행자",apply:"진행자로 지원"},
  "zh-hans":{nav:{experience:"体验",about:"关于",attend:"参加",facilitate:"带领",menu:"菜单",close:"关闭"},reserve:"预订席位",ask:"提出问题",embody:"亲身感受",explore:"探索体验",day:"白昼",dusk:"黄昏",slogan:["疗愈灵魂。","唤醒感官。"],place:"越南岘港",dates:"2027年1月12–26日",series:"MODUS系列",glanceTitle:"岘港，\n越南",glanceSub:"体验\n一览。",glanceLead:"在城市、海洋与群山之间，选择七天或完整十四天。",seven:"7天",fourteen:"14天",small:"小型亲密团体。住宿与交通另计。",compare:"比较7天与14天",included:"查看包含内容",entity:"ASCENSION是一场于2027年1月12日至26日在越南岘港举行的七天或十四天沉浸式疗愈与文化体验，以不用针的越南面诊体系为核心。",sixWays:"进入当下的\n六种方式。",passport:"你的ASCENSION护照",experienceRhythm:"你的体验。\n你的节奏。",curatedFreedom:"跟随精心策划的计划，同时保留自由。",passportBody:"ASCENSION护照开启已确认的共享体验，同时为休息、探索岘港和选择私人项目留出空间。",faqKicker:"抵达之前",faqTitle:"问题，\n解答。",facilitator:"导师",apply:"申请带领"}
};

const faqShared = {
  fr:[["Qu’est-ce qu’ASCENSION?","Une expérience conçue de 7 ou 14 jours reliant bien-être vietnamien, mouvement, son, gastronomie, culture et créativité à Da Nang."],["Qu’est-ce que le Diện Chẩn?","Une méthode vietnamienne moderne sans aiguilles associant réflexologie, acupression, chaleur, étirements et travail du corps entier."],["Qui sont les intervenants?","La Dre Huỳnh Bảo Loan dirige le Diện Chẩn quotidiennement. Les autres intervenants seront annoncés après confirmation."],["L’hébergement et les vols sont-ils inclus?","Non. Les participants réservent eux-mêmes hébergement, vols et transports locaux."],["Quelle est la politique d’annulation?","Un acompte de 300 USD réserve votre place. Le solde est dû 30 jours avant le 12 janvier 2027. Annulation à 60 jours ou plus : remboursement intégral moins 25 USD; 30–60 jours : 50 %; moins de 30 jours : non remboursable."]],
  ko:[["ASCENSION은 무엇인가요?","다낭에서 베트남 웰니스, 움직임, 소리, 음식, 문화와 창조성을 연결하는 7일 또는 14일의 큐레이션 경험입니다."],["디엔쩐이란 무엇인가요?","반사요법, 바늘 없는 지압, 온열, 스트레칭과 전신 작업을 결합한 현대 베트남 방식입니다."],["진행자는 누구인가요?","Huỳnh Bảo Loan 박사가 매일 디엔쩐을 진행합니다. 추가 진행자는 계약 확정 후 발표됩니다."],["숙박과 항공편이 포함되나요?","아니요. 참가자가 숙박, 항공편과 현지 교통을 직접 예약합니다."],["취소 정책은 무엇인가요?","300달러 보증금으로 자리를 예약하며 잔금은 2027년 1월 12일 30일 전까지입니다. 60일 이상 전 취소는 25달러 수수료를 제외하고 전액, 30–60일 전은 50%, 30일 미만은 환불되지 않습니다."]],
  "zh-hans":[["ASCENSION是什么？","一场在岘港连接越南疗愈、运动、声音、美食、文化与创造力的7天或14天策划体验。"],["什么是面诊？","一种结合反射疗法、无针指压、热疗、拉伸与全身工作的现代越南体系。"],["导师是谁？","Huỳnh Bảo Loan医生每日带领面诊。其他导师将在协议确认后公布。"],["住宿和机票包括在内吗？","不包括。参与者自行预订住宿、机票和当地交通。"],["取消政策是什么？","支付300美元订金保留席位，余额须在2027年1月12日前30天付清。提前60天以上取消可全额退款并扣除25美元管理费；提前30–60天退还50%；少于30天不退款。"]]
};
export const translatedFaq = faqShared;
export const translatedPassport = Object.fromEntries(Object.keys(shared).map(locale => [locale, shared[locale].sensoryStories.map(s => ({name:s.name,copy:s.mobile}))]));

export const translatedLower = {
  fr:{rhythmTitle:"Un rythme, pas un horaire rigide.",rhythm:"Les matins peuvent commencer par le mouvement, le souffle ou le Diện Chẩn. Les journées s’ouvrent sur la gastronomie, la culture, la création et la restauration. Les soirées peuvent apporter son, danse, communauté ou calme.",times:[["Matin","Mouvement · Souffle · Océan"],["Midi","Restaurer · Explorer · Créer"],["Crépuscule","Son · Table partagée · Connexion"],["Votre temps","Plage · Spa · Ville · Repos · Séances privées"]],note:"ASCENSION est conçu, pas prescrit.",hostKicker:"Pourquoi j’ai créé ASCENSION",hostTitle:"Vécu avant d’être proposé.",host1:"ASCENSION est né de mon parcours personnel entre mouvement, créativité, bien-être traditionnel vietnamien et vie à Da Nang.",host2:"Construit autour du Diện Chẩn et enrichi par des praticiens choisis, il éveille le corps, les sens et l’imagination.",comparisonKicker:"Choisissez votre rythme",comparisonTitle:"Sept jours ou quatorze.",program:"programme",stay:"Votre séjour, à votre façon",travelTitle:"Programme et destination. L’hébergement est séparé.",travel:"Choisissez et réservez l’hôtel de Da Nang qui vous convient. Vols, hébergement et transports locaux ne sont pas inclus.",attendanceTitle:"Réservez votre ASCENSION.",attendanceLead:"Les programmes commencent à 1 200 USD. Un acompte de 300 USD réserve votre place.",included:"Inclus",includedItems:["Accès au programme ASCENSION conçu autour du mouvement, de la restauration, du son, du goût, de la découverte et de la création","Participation au groupe ASCENSION"],optional:"En option · Réserver séparément",optionalItems:["Hébergement — chacun choisit et réserve son hôtel","Vols et transports locaux","Soins privés et services de spa supplémentaires","Excursions, repas ou expériences supplémentaires"],deposit:"Le paiement actif demande un acompte de réservation de 300 USD.",seriesTitle:"Une idée. Plusieurs lieux.",series:"ASCENSION n’est pas une retraite unique, mais une série itinérante d’éditions conçues autour du bien-être, du mouvement, du son et du lieu.",current:"Expérience principale actuelle",planning:"Édition 02 · En préparation",follow:"Édition suivante",next:"Suivante",perhaps:"Peut-être votre ville.",request:"Demander ASCENSION dans votre ville",waiting:"Da Nang vous attend."},
  ko:{rhythmTitle:"고정된 일정이 아닌 리듬.",rhythm:"아침은 움직임, 호흡 또는 디엔쩐으로 시작할 수 있습니다. 낮에는 음식, 문화, 창작과 회복이 열리고 저녁에는 소리, 춤, 공동체 또는 고요가 찾아옵니다.",times:[["아침","움직임 · 호흡 · 바다"],["한낮","회복 · 탐험 · 창조"],["해질녘","소리 · 함께하는 식탁 · 연결"],["나의 시간","해변 · 스파 · 도시 · 휴식 · 개인 세션"]],note:"ASCENSION은 큐레이션되지만 강요되지 않습니다.",hostKicker:"ASCENSION을 만든 이유",hostTitle:"경험한 뒤에 제안합니다.",host1:"ASCENSION은 움직임, 창조성, 베트남 전통 웰니스와 다낭에서의 삶을 통한 개인적 여정에서 시작되었습니다.",host2:"디엔쩐을 중심으로 선정된 실천가들과 확장되어 몸, 감각과 상상력을 깨우는 몰입형 경험입니다.",comparisonKicker:"나의 리듬 선택",comparisonTitle:"7일 또는 14일.",program:"프로그램",stay:"나만의 방식으로 머물기",travelTitle:"프로그램과 장소. 숙박은 별도입니다.",travel:"자신에게 맞는 다낭 호텔을 직접 선택하고 예약하세요. 항공편, 숙박과 현지 교통은 포함되지 않습니다.",attendanceTitle:"ASCENSION 자리 예약.",attendanceLead:"프로그램은 1,200 USD부터이며 300 USD 보증금으로 자리를 예약합니다.",included:"포함",includedItems:["움직임, 회복, 소리, 맛, 탐험과 창작으로 구성된 ASCENSION 프로그램 이용","ASCENSION 공동 그룹 참여"],optional:"선택 사항 · 별도 예약",optionalItems:["숙박 — 참가자가 호텔 직접 선택·예약","항공편과 현지 교통","개인 치료와 추가 스파 서비스","추가 투어, 식사 또는 특별 경험"],deposit:"결제 페이지에서 300 USD 예약 보증금을 요청합니다.",seriesTitle:"하나의 아이디어. 여러 장소.",series:"ASCENSION은 하나의 리트리트가 아니라 웰니스, 움직임, 소리와 장소를 중심으로 각 도시에 맞춰지는 순회형 큐레이션 시리즈입니다.",current:"현재의 주요 경험",planning:"에디션 02 · 기획 중",follow:"다음 에디션",next:"다음",perhaps:"당신의 도시일 수도 있습니다.",request:"당신의 도시에 ASCENSION 요청",waiting:"다낭이 기다립니다."},
  "zh-hans":{rhythmTitle:"一种节奏，而非僵硬日程。",rhythm:"清晨可以从运动、呼吸或面诊开始。白天走向美食、文化、创造与修复；夜晚可能带来声音、舞动、社群或宁静。",times:[["清晨","运动 · 呼吸 · 海洋"],["正午","修复 · 探索 · 创造"],["黄昏","声音 · 共享餐桌 · 连接"],["你的时间","海滩 · 水疗 · 城市 · 休息 · 私人项目"]],note:"ASCENSION经过策划，但不强制。",hostKicker:"我为何创立ASCENSION",hostTitle:"亲身经历之后，才与你分享。",host1:"ASCENSION源于我在运动、创造、越南传统疗愈和岘港生活中的个人旅程。",host2:"它以面诊为核心，并由精选实践者拓展，旨在唤醒身体、感官与想象力。",comparisonKicker:"选择你的节奏",comparisonTitle:"七天或十四天。",program:"项目",stay:"按你的方式停留",travelTitle:"项目与地点。住宿另计。",travel:"请选择并预订适合自己的岘港酒店。机票、住宿和当地交通不包含在项目价格中。",attendanceTitle:"预订你的ASCENSION。",attendanceLead:"项目价格从1,200美元起，支付300美元订金即可保留席位。",included:"包含",includedItems:["参与涵盖运动、修复、声音、味觉、探索和创造的ASCENSION策划项目","加入ASCENSION共同团体"],optional:"可选 · 另行预订",optionalItems:["住宿——自行选择并预订酒店","机票与当地交通","私人治疗与额外水疗服务","额外游览、餐食或特别体验"],deposit:"当前支付页面收取300美元预订订金。",seriesTitle:"一个想法。许多地方。",series:"ASCENSION并非单一静修，而是一系列围绕健康、运动、声音与地点打造，并由落脚之地塑造的巡回策划版本。",current:"当前主要体验",planning:"第02期 · 计划中",follow:"后续版本",next:"下一站",perhaps:"也许是你的城市。",request:"邀请ASCENSION来到你的城市",waiting:"岘港在等你。"}
};
