/**
 * Central media registry for the six ASCENSION sensory chapters.
 * Replace temporary or pending entries here; chapter layout should not need to change.
 */
export const sensoryMedia = {
  embody: {
    type: "video",
    src: "https://res.cloudinary.com/dno3ruh4b/video/upload/w_622,h_368,c_scale/v1788096436/hf_20260830_041430_e38407f9-d6d0-4bfd-8bc7-4635dc83c4a4_dbe2og.mp4",
    poster: "https://res.cloudinary.com/dno3ruh4b/image/upload/f_auto,q_auto/v1787809245/hf_20260826_211528_f5a526bc-fb5d-4b35-bce6-9c5f6777d724_jmqpoi.png",
    alt: "An illustration of restorative touch and bodywork",
    focalPointMobile: "50% 50%",
    focalPointDesktop: "50% 50%",
    status: "temporary",
    productionLabel: "EMBODY — FINAL MOVEMENT MEDIA PENDING",
  },
  see: {
    type: "youtube",
    videoId: "Ehku63B2pzQ",
    poster: "https://i.ytimg.com/vi/Ehku63B2pzQ/maxresdefault.jpg",
    alt: "Preview frame from the selected ASCENSION SEE film",
    focalPointMobile: "50% 50%",
    focalPointDesktop: "50% 50%",
    status: "approved-sample",
    productionLabel: "SEE — FEATURED FILM",
  },
  sound: {
    type: "audio-video",
    poster: "https://res.cloudinary.com/dno3ruh4b/image/upload/f_auto,q_auto/v1787663022/ear_sound_topographic_parchment_d1tm3s.webp",
    filmPoster: "https://i.ytimg.com/vi/w1ucZCmvO5c/maxresdefault.jpg",
    filmId: "w1ucZCmvO5c",
    meditationId: "x6UITRjhijI",
    alt: "An illustration of an ear surrounded by radiating sound waves",
    focalPointMobile: "50% 50%",
    focalPointDesktop: "50% 50%",
    status: "approved-sample",
    productionLabel: "SOUND — EXTERNAL LISTENING SAMPLES",
  },
  taste: {
    type: "youtube",
    videoId: "obRDCiSwjCs",
    poster: "https://i.ytimg.com/vi/obRDCiSwjCs/maxresdefault.jpg",
    alt: "Preview frame from the selected ASCENSION TASTE film",
    focalPointMobile: "50% 50%",
    focalPointDesktop: "50% 50%",
    status: "approved-sample",
    productionLabel: "TASTE — FEATURED FILM",
  },
  breathe: {
    type: "video",
    src: "https://res.cloudinary.com/dno3ruh4b/video/upload/v1788363812/holographic-human-body-x-ray-scan-with-respiratory-2026-04-22-16-04-13-utc_d8oqa0.mp4",
    poster: "https://res.cloudinary.com/dno3ruh4b/video/upload/so_0,f_jpg,q_auto/v1788363812/holographic-human-body-x-ray-scan-with-respiratory-2026-04-22-16-04-13-utc_d8oqa0.jpg",
    alt: "A holographic visualization of breath moving through the human body",
    focalPointMobile: "50% 50%",
    focalPointDesktop: "50% 50%",
    status: "approved",
    productionLabel: "BREATHE — APPROVED RESPIRATORY FILM",
  },
  create: {
    type: "video",
    src: "https://res.cloudinary.com/dno3ruh4b/video/upload/a_90,q_auto/v1788259482/Angel_Art_Daniel_Stanford_Da_Nang_fps2la.mp4",
    poster: "https://res.cloudinary.com/dno3ruh4b/video/upload/a_90,so_0,f_jpg,q_auto/v1788259482/Angel_Art_Daniel_Stanford_Da_Nang_fps2la.jpg",
    alt: "A hand applying gold leaf detail to a painted portrait",
    focalPointMobile: "50% 50%",
    focalPointDesktop: "50% 50%",
    status: "temporary",
    productionLabel: "SIXTH SENSE — FINAL CREATIVE MEDIA PENDING",
  },
};
