import InfoPage from "./info-page";
import { PRACTITIONER_APPLICATION, RESERVATION_URL } from "../seo";

export function VietnameseAboutPage() { return <InfoPage locale="vi" eyebrow="Giới thiệu" title="Được trải nghiệm trước khi được trao tặng." lead="ASCENSION phát triển từ hành trình cá nhân của Daniel Stanford qua chuyển động, sáng tạo, chăm sóc sức khỏe truyền thống Việt Nam và cuộc sống tại Đà Nẵng."><section><h2>Một trải nghiệm được tuyển chọn</h2><p>ASCENSION không được ghép lại từ xu hướng. Trải nghiệm bắt đầu từ nhiều tháng Daniel trực tiếp thực hành Diện Chẩn tại Đà Nẵng, trong đó có 40 ngày trị liệu liên tục.</p><p>Nền tảng ấy được mở rộng qua chuyển động, âm thanh, ẩm thực, văn hóa và sáng tạo—tất cả trong một nhịp điệu cho phép mỗi người tự lựa chọn.</p></section><section><h2>Một chuỗi của MODUS</h2><p>ASCENSION là chuỗi do MODUS — Taste Intelligence, Stanford Emporium Inc., Montréal khởi xướng và xuất bản. Đà Nẵng là Kỳ 01 của một ý tưởng được tạo ra để đi đến nhiều nơi.</p></section></InfoPage>; }

export function VietnameseAttendPage() { return <InfoPage locale="vi" eyebrow="Tham dự" title="Bảy ngày hoặc mười bốn ngày." lead="Tham gia kỳ ASCENSION đầu tiên tại Đà Nẵng, Việt Nam, từ ngày 12 đến 26 tháng 1 năm 2027."><section className="info-options" aria-label="Lựa chọn chương trình"><article><p className="info-eyebrow">Bảy ngày</p><h2>12–19 tháng 1, 2027</h2><p className="info-price">1.200 USD</p><p>Bước vào nhịp điệu chung của ASCENSION trong một tuần, vẫn tự do chọn điều phù hợp với bạn.</p><a className="text-action" href={RESERVATION_URL}>Đặt chương trình bảy ngày →</a></article><article><p className="info-eyebrow">Mười bốn ngày</p><h2>12–26 tháng 1, 2027</h2><p className="info-price">2.000 USD</p><p>Trải nghiệm trọn hành trình qua chăm sóc sức khỏe, chuyển động, âm thanh, ẩm thực, văn hóa và sáng tạo Việt Nam.</p><a className="text-action" href={RESERVATION_URL}>Đặt chương trình mười bốn ngày →</a></article></section><section><h2>Trải nghiệm bao gồm gì</h2><p>Hộ chiếu ASCENSION mở ra chương trình chung đã xác nhận, xây quanh Diện Chẩn. Chuyển động, hơi thở, khám phá văn hóa, sáng tạo và một số trải nghiệm ẩm thực chung nằm trong chương trình rộng hơn.</p></section><section><h2>Đi lại và chỗ ở</h2><p>Chỗ ở, chuyến bay và di chuyển địa phương tính riêng. Khách tự chọn và đặt chỗ ở. Không cần kinh nghiệm trước về chuyển động, thiền, trị liệu cơ thể hay sáng tạo.</p></section></InfoPage>; }

export function VietnameseDienChanPage() { return <InfoPage locale="vi" eyebrow="Diện Chẩn" title="Một cơ thể. Mọi thứ đều kết nối." lead="Diện Chẩn là phương pháp chăm sóc sức khỏe Việt Nam không dùng kim, tạo nên nền tảng trị liệu của ASCENSION."><section><h2>Diện Chẩn là gì?</h2><p>Diện Chẩn là một phương pháp hiện đại của Việt Nam, bắt nguồn từ các nguyên lý truyền thống. Phương pháp kết hợp phản xạ học, day ấn huyệt không dùng kim, nhiệt trị liệu, kéo giãn và thao tác toàn thân theo từng người.</p><p>Khuôn mặt có thể là điểm khởi đầu, nhưng buổi thực hành không giới hạn ở phản xạ vùng mặt.</p><p><strong>Các buổi Diện Chẩn hằng ngày do BS. Huỳnh Bảo Loan, Đà Nẵng, phụ trách.</strong></p></section><section><h2>Diện Chẩn có dùng kim không?</h2><p>Không. Diện Chẩn không dùng kim, không nên được mô tả là châm cứu và không theo một quy trình chung cho tất cả.</p></section><section><h2>Vai trò trong ASCENSION</h2><p>Diện Chẩn tạo nền tảng Việt Nam đặc trưng cho trải nghiệm rộng hơn. Đây là thực hành chăm sóc sức khỏe truyền thống và trải nghiệm giáo dục, không thay thế chẩn đoán hay điều trị y tế.</p></section></InfoPage>; }

export function VietnameseFacilitatePage() { return <InfoPage locale="vi" eyebrow="Hướng dẫn" title="Mang thực hành của bạn đến Đà Nẵng." lead="Đang nhận hồ sơ người hướng dẫn cho kỳ ASCENSION đầu tiên tại Đà Nẵng, 12–26 tháng 1 năm 2027." primaryLabel="Đăng ký hướng dẫn" primaryHref={PRACTITIONER_APPLICATION}><section><h2>ASCENSION đang mời ai</h2><p>Chúng tôi chào đón hồ sơ từ những người giàu kinh nghiệm trong chuyển động, hơi thở, thiền hướng dẫn, tắm âm thanh, trị liệu cơ thể, sáng tạo và thực hành sức khỏe bổ trợ.</p></section><section><h2>Cách lựa chọn</h2><p>Việc lựa chọn dựa trên kinh nghiệm, tính chính trực, sự phù hợp văn hóa, thực hành tôn trọng sự đồng thuận và đóng góp có ý nghĩa cho một nhóm quốc tế nhỏ.</p></section><section><h2>Cách đăng ký</h2><p>Email đăng ký sẽ hỏi địa điểm, phương pháp, đào tạo, kinh nghiệm, hồ sơ nghề nghiệp, đề xuất đóng góp, thời gian và yêu cầu thực tế của bạn.</p></section></InfoPage>; }

export function VietnameseTermsPage() { return <InfoPage locale="vi" eyebrow="Điều khoản" title="Điều khoản rõ ràng trước khi đặt chỗ." lead="Các điều khoản này áp dụng cho ASCENSION SENSES · Đà Nẵng, 12–26 tháng 1 năm 2027." primaryLabel="Xem lựa chọn tham dự" primaryHref="/vi/attend"><section><h2>Đặt chỗ và thanh toán</h2><p>Khoản đặt cọc 300 USD giữ chỗ. Số dư chương trình đến hạn 30 ngày trước ngày 12 tháng 1 năm 2027.</p></section><section><h2>Chính sách hủy</h2><p>Hủy trước từ 60 ngày: hoàn đủ, trừ phí hành chính 25 USD. Hủy trước 30–60 ngày: hoàn 50% số tiền đã trả. Hủy dưới 30 ngày: không hoàn tiền. Các buổi riêng không được hoàn tiền sau khi đặt.</p></section><section><h2>Đi lại và chỗ ở</h2><p>Chỗ ở, chuyến bay và di chuyển địa phương không bao gồm trong giá. Khách tự chọn và đặt chỗ ở.</p></section><section><h2>Trải nghiệm sức khỏe và giáo dục</h2><p>ASCENSION là trải nghiệm chăm sóc sức khỏe và giáo dục, không phải chăm sóc y tế và không thay thế chẩn đoán hay điều trị chuyên môn.</p></section></InfoPage>; }

export function VietnamesePrivacyPage() { return <InfoPage locale="vi" eyebrow="Quyền riêng tư" title="Thông tin của bạn được xử lý cẩn trọng." lead="Thông báo này giải thích thông tin giới hạn được dùng để vận hành website và trả lời yêu cầu." primaryLabel="Trở về ASCENSION" primaryHref="/vi"><section><h2>Thông tin bạn cung cấp</h2><p>Chúng tôi nhận thông tin khi bạn gửi email, yêu cầu thông tin, đăng ký hướng dẫn hoặc hoàn tất đặt chỗ qua trang thanh toán của bên thứ ba. Vui lòng không gửi thông tin sức khỏe riêng tư qua email chung.</p></section><section><h2>Dữ liệu website và dịch vụ</h2><p>Website có thể thu thập dữ liệu kỹ thuật và sử dụng giới hạn qua Vercel Analytics. Stripe xử lý thanh toán; Cloudinary, Vimeo và YouTube có thể xử lý thông tin kỹ thuật khi nội dung đa phương tiện được tải hoặc phát.</p></section><section><h2>Cách sử dụng thông tin</h2><p>Thông tin được dùng để trả lời yêu cầu, quản lý hồ sơ và đặt chỗ, cải thiện website, duy trì bảo mật và tuân thủ nghĩa vụ pháp lý. ASCENSION SENSES không bán thông tin cá nhân.</p></section></InfoPage>; }
